spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/johnie_boot
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    defer-datasource-initialization: true
#  sql:
#    init:
##      data-locations: classpath:sql/data.sql
#      schema-locations: classpath:sql/schema.sql
#      mode: always
