
### 注册
POST http://localhost:9090/api/v1/auth/register
Content-Type: application/json

{
  "email": "johniecheng@gmail.com",
  "password": "Cheng123456"
}

### 登录
POST http://localhost:9090/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "johniecheng@gmail.com",
  "password": "Cheng123456"
}

> {%
    client.global.set("accessToken", response.body["accessToken"]);
%}

### 删除用户
< {%
    request.variables.set("auth_token", client.global.get("accessToken"))
%}
DELETE http://localhost:9090/api/v1/user/4
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### 添加用户
< {%
    request.variables.set("auth_token", client.global.get("accessToken"))
%}
POST http://localhost:9090/api/v1/user
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "email": "johniecheng1@gmail.com",
  "password": "$2a$10$54CNo2AiAmSpTIEeAZgOJ.pZTwXTSCruHsp24kXtQMBUkLY9yMk/O",
  "role": [],
  "version": 0,
  "id": null,
  "createBy": "johnie",
  "createDate": 1681117610550,
  "updateBy": "johnie",
  "updateDate": 1681117610550
}
