### 更新用户
< {%
    request.variables.set("auth_token", client.global.get("accessToken"))

%}
PUT http://localhost:9090/api/v1/sys-user
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 4,
  "username": "johniecheng@gmail.com",
  "password": "Cheng1234567",
  "sysDepartmentNo": "1001",
  "sysRoleNos": "10001"
}

### 删除用户
< {%
    request.variables.set("auth_token", client.global.get("accessToken"))

%}
DELETE http://localhost:9090/api/v1/sys-user/2
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### 添加用户
< {%
    request.variables.set("auth_token", client.global.get("accessToken"))
%}
POST http://localhost:9090/api/v1/sysUser
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "email": "johniecheng1@gmail.com",
  "password": "$2a$10$54CNo2AiAmSpTIEeAZgOJ.pZTwXTSCruHsp24kXtQMBUkLY9yMk/O",
  "role": [],
  "version": 0,
  "id": null,
  "createBy": "johnie",
  "createDate": 1681117610550,
  "updateBy": "johnie",
  "updateDate": 1681117610550
}
